Repository wecode-bootcamp-korea/41-1st-Dr.Bean-backend, pull requests merged in 2023-01, with the labels that each got.

#1 [ADD] 41기 DR.Bean Backend 초기 환경 세팅
  .env.sample
  .gitignore
  api/controllers/index.js
  api/middleware/auth.js
  api/models/dbconfig.js
  api/routes/index.js
  api/services/index.js
  app.js
  package-lock.json
  package.json
Labels: 멘토 리뷰 요청

#2 [ADD] 41기 Dr.Bean 데이터베이스 Backend 데이터베이스 생성
  .env.sample
  .gitignore
  app.js
  db/migrations/20230103111740_create_users_table.sql
  db/migrations/20230103111741_create_users_address_table.sql
  db/migrations/20230103111742_create_review_images_table.sql
  db/migrations/20230103111743_create_size_options_table.sql
  db/migrations/20230103111744_create_grind_options_table.sql
  db/migrations/20230103111745_create_categories_table.sql
  db/migrations/20230103111746_create_item_images_table.sql
  db/migrations/20230103111747_create_order_status_table.sql
  db/migrations/20230103111809_create_items_table.sql
  db/migrations/20230103111810_create_reviews_table.sql
  db/migrations/20230103111811_create_item_options_table.sql
  db/migrations/20230103111812_create_carts_table.sql
  db/migrations/20230103112225_create_orders_table.sql
  db/migrations/20230103112656_create_order_items_table.sql
  db/migrations/20230103112712_create_payments_table.sql
Labels: 멘토 리뷰 요청

#3 [ADD] 41기 Dr.Bean 로그인/회원가입 기능 추가
  api/controllers/userController.js
  api/middleware/auth.js
  api/models/dbconfig.js
  api/models/userDao.js
  api/routes/index.js
  api/routes/userRouter.js
  api/services/userService.js
  db/migrations/20230103111740_create_users_table.sql
  db/migrations/20230103111746_create_item_images_table.sql
  db/migrations/20230103111809_create_items_table.sql
  db/migrations/20230103111813_create_order_items_table.sql
Labels: 멘토 리뷰 요청

#4 [ADD] items 카테고리별 GET 및 상세페이지 POST
  api/controllers/index.js
  api/controllers/itemsControllers.js
  api/models/itemsDao.js
  api/routes/index.js
  api/routes/itemsRouter.js
  api/services/index.js
  api/services/itemsServices.js
  db/migrations/20230103111740_create_users_table.sql
  db/migrations/20230103111809_create_items_table.sql
Labels: Conflict 해결 요청

#7 [MODIFY] db 수정으로 인한 쿼리문 수정
  api/controllers/itemsControllers.js
  api/models/itemsDao.js
Labels: 멘토 리뷰 요청

#6 [MODIFY] migration 수정 및 추가
  db/migrations/20230103111742_create_review_images_table.sql
  db/migrations/20230103111745_create_categories_table.sql
  db/migrations/20230103111809_create_items_table.sql
  db/migrations/20230103112712_create_payments_table.sql
  db/migrations/20230106041047_create_sub_categories.sql
Labels: Conflict 해결 요청

#8 [ADD] 토큰값으로 유저 정보 불러오기
  api/controllers/orderControllers.js
  api/controllers/userController.js
  api/models/orderDao.js
  api/routes/index.js
  api/routes/orderRouter.js
  api/services/orderServices.js
Labels: 멘토 리뷰 요청

#11 [MODIFY] items sql 쿼리문 수정
  api/models/itemsDao.js
Labels: 멘토 리뷰 요청

#10 [ADD] 결제 리스트 및 유저정보, 옵션관련
  api/controllers/orderControllers.js
  api/models/orderDao.js
  api/routes/orderRouter.js
  api/services/orderServices.js
Labels: 멘토 리뷰 요청

#5 [MODIFY] 충돌 해결
  api/controllers/cartController.js
  api/controllers/itemsControllers.js
  api/controllers/userController.js
  api/middleware/auth.js
  api/models/cartDao.js
  api/models/userDao.js
  api/routes/cartRouter.js
  api/routes/index.js
  api/routes/itemsRouter.js
  api/routes/userRouter.js
  api/services/cartService.js
  api/services/itemsServices.js
  api/services/userService.js
Labels: 멘토 리뷰 요청

#13 [CONFLICT] 수정 및 features 병합
  api/controllers/itemsControllers.js
  api/middleware/auth.js
  api/models/itemsDao.js
  api/routes/index.js
  api/routes/itemsRouter.js
  api/services/itemsServices.js
Labels: Conflict 해결 요청, 수정 요청

#18 [ADD] cartjs 파일 오타수정
  api/routes/cartRouter.js
  api/services/cartServices.js
Labels: 멘토 리뷰 요청

#20 [MODIFY] usercontroller jwtToken 이름 변경
  api/controllers/userController.js
Labels: 멘토 리뷰 요청

#21 [MODIFY] getItemReviews offset, limit 기능 수정
  api/controllers/itemsControllers.js
  api/models/itemsDao.js
  api/routes/itemsRouter.js
  api/services/itemsServices.js
Labels: 멘토 리뷰 요청

#23 [MODIFY] addressAndItems itemOptions query 추가 및 order_items quantity …
  api/models/orderDao.js
Labels: 수정 요청
